# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Octunnel < Formula
  desc "Expose OpenCode server via Cloudflare Tunnel"
  homepage "https://github.com/chabinhwang/octunnel"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chabinhwang/octunnel/releases/download/v0.1.0/octunnel_darwin_amd64.tar.gz"
      sha256 "d7061a73368060824d8c9286092f62bb46f0a51a237b5cbebe04fd9fb4d78a0d"

      define_method(:install) do
        bin.install "octunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chabinhwang/octunnel/releases/download/v0.1.0/octunnel_darwin_arm64.tar.gz"
      sha256 "7683017c9388b6f092eb26fb38d59de8c9eef954d011827ed4f8380f586ceae8"

      define_method(:install) do
        bin.install "octunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chabinhwang/octunnel/releases/download/v0.1.0/octunnel_linux_amd64.tar.gz"
      sha256 "c15dd78718b61aa0504b69cdc625212d4fbbe12837b5f0f61e18989acc3c28cc"
      define_method(:install) do
        bin.install "octunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chabinhwang/octunnel/releases/download/v0.1.0/octunnel_linux_arm64.tar.gz"
      sha256 "3ec4b3042cb6beb0e33ddfc87a967d29b014348fdd451358572d75e3fe46c414"
      define_method(:install) do
        bin.install "octunnel"
      end
    end
  end

  test do
    system "#{bin}/octunnel", "--help"
  end
end
